name: Create PR on Release
on:
  release:
    types: [created]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create new branch and PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          TAG_NAME=${{ github.event.release.tag_name }}
          BRANCH_NAME="release/${TAG_NAME}"
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
          gh pr create --title ":rocket: Release ${TAG_NAME}" --body "" --base main --head $BRANCH_NAME